name: mealplanner-db

services:
    postgres:
        image: postgres:16-alpine
        container_name: mealplanner-postgres
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "${HOST_PORT:-5432}:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}",
                ]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    pg_data:
        name: mealplanner_pg_data
